# Generated by Django 4.1.1 on 2022-10-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_profile_projectguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workexp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
