# Generated by Django 4.1.1 on 2022-10-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_workexp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='projectdesc',
            new_name='projectdesc1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='projectname',
            new_name='projectname1',
        ),
        migrations.AddField(
            model_name='profile',
            name='projectdesc2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='projectname2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
